service: service-users

provider:
  name: aws
  runtime: nodejs12.x

package:
  exclude:
    - node_modules/**

plugins:
  - serverless-webpack

resources:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: users
    KeySchema:
      - AttributeName: hk
        KeyType: HASH
      - AttributeName: sk
        KeyType: RANGE